# Generated by Django 4.1.3 on 2024-02-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datareporting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meps_comp_entries',
            name='school_or_private',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
