# Generated by Django 4.1.3 on 2024-02-28 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datareporting', '0002_alter_meps_comp_entries_school_or_private'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=30, null=True)),
                ('last_updated', models.DateTimeField()),
                ('series_parameter', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManualTaskQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_creation_date', models.DateTimeField(auto_now_add=True)),
                ('task_completion_date', models.DateTimeField(null=True)),
                ('task_queued', models.IntegerField(default=1)),
                ('task_running', models.IntegerField(default=0)),
                ('report_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_queue', to='datareporting.reports')),
            ],
        ),
    ]
