# Generated by Django 4.1.3 on 2024-02-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datareporting', '0003_reports_manualtaskqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='last_triggered',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='last_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
