# Generated by Django 4.1.3 on 2024-02-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datareporting', '0004_reports_last_triggered_alter_reports_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='error_status',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
