# Generated by Django 4.2.6 on 2024-03-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datareporting', '0005_reports_error_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='cie_ciedirect_enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sesid', models.CharField(max_length=8, null=True)),
                ('epsenquiryid', models.CharField(max_length=9, null=True)),
            ],
        ),
    ]
