# Generated by Django 4.2.6 on 2024-03-11 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datareporting', '0006_cie_ciedirect_enquiry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cie_ciedirect_enquiry',
            new_name='ciedirect_enquiry',
        ),
    ]
