# Generated by Django 4.2.6 on 2024-03-11 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datareporting', '0007_rename_cie_ciedirect_enquiry_ciedirect_enquiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ciedirect_enquiry',
            old_name='sesid',
            new_name='sessid',
        ),
    ]
