# Generated by Django 4.2.6 on 2024-03-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datareporting', '0008_rename_sesid_ciedirect_enquiry_sessid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ciedirect_enquirystatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiryid', models.CharField(max_length=8, null=True)),
                ('enquirystatus', models.CharField(max_length=12, null=True)),
                ('datetime', models.DateField()),
            ],
        ),
    ]
