# Generated by Django 4.2.6 on 2024-03-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datareporting', '0009_ciedirect_enquirystatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='parameter_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
