# Generated by Django 4.2.6 on 2024-03-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datareporting', '0010_reports_parameter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciedirect_enquirystatus',
            name='enquiryid',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ciedirect_enquirystatus',
            name='enquirystatus',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
