# Generated by Django 4.2.6 on 2024-03-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datareporting', '0011_alter_ciedirect_enquirystatus_enquiryid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='centre_enquiry_requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=10, null=True)),
                ('ses_sid', models.CharField(max_length=8, null=True)),
                ('cnu_id', models.CharField(max_length=8, null=True)),
                ('status', models.CharField(max_length=2, null=True)),
                ('created_datetime', models.DateField()),
                ('completed_datetime', models.DateField()),
            ],
        ),
    ]
