# Generated by Django 4.2.6 on 2024-03-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datareporting', '0012_centre_enquiry_requests'),
    ]

    operations = [
        migrations.CreateModel(
            name='enquiry_request_parts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=6, null=True)),
                ('cer_sid', models.CharField(max_length=6, null=True)),
                ('es_service_code', models.CharField(max_length=5, null=True)),
                ('booked_in_error_ind', models.CharField(max_length=5, null=True)),
            ],
        ),
    ]
