# Generated by Django 4.2.6 on 2024-03-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datareporting', '0013_enquiry_request_parts'),
    ]

    operations = [
        migrations.CreateModel(
            name='enquiry_components',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=10, null=True)),
                ('ccm_ass_code', models.CharField(max_length=5, null=True)),
                ('ccm_asv_ver_no', models.CharField(max_length=5, null=True)),
                ('ccm_com_id', models.CharField(max_length=5, null=True)),
            ],
        ),
    ]
