# Generated by Django 4.2.6 on 2024-03-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datareporting', '0014_enquiry_components'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry_request_parts',
            name='cer_sid',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry_request_parts',
            name='sid',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
