# Generated by Django 4.2.6 on 2024-03-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datareporting', '0015_alter_enquiry_request_parts_cer_sid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry_components',
            name='sid',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
