# Generated by Django 4.2.6 on 2024-03-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datareporting', '0016_alter_enquiry_components_sid'),
    ]

    operations = [
        migrations.CreateModel(
            name='all_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ses_sid', models.CharField(max_length=15, null=True)),
                ('ass_code', models.CharField(max_length=5, null=True)),
                ('asv_ver_no', models.CharField(max_length=5, null=True)),
                ('com_id', models.CharField(max_length=5, null=True)),
                ('qua_name', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
