# Generated by Django 4.2.6 on 2024-03-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datareporting', '0017_all_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='row_count',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
