# Generated by Django 4.2.6 on 2024-03-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datareporting', '0018_reports_row_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='row_count',
            field=models.IntegerField(default=0),
        ),
    ]
