# Generated by Django 4.2.6 on 2024-03-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datareporting', '0019_alter_reports_row_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciedirect_enquiry',
            name='enquiryid',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
