# Generated by Django 4.2.6 on 2024-03-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datareporting', '0020_ciedirect_enquiry_enquiryid'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry_components',
            name='erp_sid',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
