# Generated by Django 4.2.6 on 2024-03-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datareporting', '0021_enquiry_components_erp_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='Active',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
