# Generated by Django 4.2.6 on 2024-03-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datareporting', '0023_remove_reports_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='Active',
            field=models.IntegerField(default=0),
        ),
    ]
