# Generated by Django 4.2.6 on 2024-03-13 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datareporting', '0024_reports_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reports',
            name='Active',
        ),
    ]
