# Generated by Django 4.2.6 on 2024-03-13 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datareporting', '0026_reports_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reports',
            old_name='Active',
            new_name='Active_Refresh',
        ),
    ]
