# Generated by Django 4.2.6 on 2024-03-13 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datareporting', '0027_rename_active_reports_active_refresh'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reports',
            old_name='Active_Refresh',
            new_name='active_refresh',
        ),
    ]
