# Generated by Django 4.2.6 on 2024-03-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datareporting', '0028_rename_active_refresh_reports_active_refresh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='row_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
