# Generated by Django 4.2.6 on 2024-03-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datareporting', '0029_alter_reports_row_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centre_enquiry_requests',
            name='completed_datetime',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='centre_enquiry_requests',
            name='created_datetime',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='ciedirect_enquirystatus',
            name='datetime',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='active_refresh',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
