# Generated by Django 4.2.6 on 2024-03-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datareporting', '0030_alter_centre_enquiry_requests_completed_datetime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Test', models.CharField(max_length=1, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='centre_enquiry_requests',
            name='completed_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='centre_enquiry_requests',
            name='created_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ciedirect_enquirystatus',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
