# Generated by Django 4.2.6 on 2024-03-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datareporting', '0036_alter_report_datasets_report_parameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='report_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
