# Generated by Django 4.2.6 on 2024-03-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datareporting', '0037_alter_reports_report_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Test', models.CharField(max_length=1, null=True)),
            ],
        ),
    ]
