# Generated by Django 4.2.6 on 2024-03-20 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datareporting', '0040_remove_datasets_active_refresh_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='all_products',
        ),
        migrations.DeleteModel(
            name='centre_enquiry_requests',
        ),
        migrations.DeleteModel(
            name='ciedirect_enquiry',
        ),
        migrations.DeleteModel(
            name='ciedirect_enquirystatus',
        ),
        migrations.DeleteModel(
            name='enquiry_components',
        ),
        migrations.DeleteModel(
            name='enquiry_request_parts',
        ),
        migrations.DeleteModel(
            name='meps_comp_entries',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='Test2',
        ),
        migrations.DeleteModel(
            name='Test3',
        ),
    ]
