# Generated by Django 4.2.6 on 2024-03-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datareporting', '0042_datasets_operator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Script_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script', models.CharField(max_length=100, null=True)),
                ('running', models.BooleanField(default=False)),
            ],
        ),
    ]
