# Generated by Django 4.2.6 on 2024-03-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datareporting', '0043_script_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='script_info',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
