services:
  web:
    build: .
    command: [  "uwsgi", "--ini", "/code/config/uwsgi/uwsgi.ini"]
    restart: always
    volumes:
      - .:/code
    environment:
     - DJANGO_SETTINGS_MODULE=redepplan.settings
    env_file:
      - .env
  apache:
    image: httpd:2.4
    restart: always
    volumes:
      - ./config/apache:/etc/httpd/
      - .:/code
    ports:
      - "80:80"
      - "443:443"