services:
  web:
    tty: true
    build: .
    ports:           # to access the container from outside
      - "8000:8000"
    #command: [  "uwsgi", "--ini", "/code/config/uwsgi/uwsgi.ini"]
    restart: always
    volumes:
      - .:/code
    environment:
     - DJANGO_SETTINGS_MODULE=redepplan.settings
    env_file:
      - .env
  apache:
    tty: true
    build: ./apache
    restart: always
    volumes:
      - ./apache/apache_django.conf:/etc/apache2/sites-available/000-default.conf
      - .:/code
    ports:
      - "81:80"
      - "443:443"