# Generated by Django 3.2.9 on 2022-02-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='personnel_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='personnel_type',
            field=models.CharField(max_length=20),
        ),
    ]
