# Generated by Django 3.2.9 on 2022-02-02 16:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_auto_20220202_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='employment_start',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
