# Generated by Django 3.2.15 on 2022-10-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test_employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(blank=True, max_length=100)),
                ('employee_ID', models.CharField(max_length=20)),
                ('employee_location', models.CharField(max_length=200)),
            ],
        ),
    ]
