# Generated by Django 3.2.9 on 2022-09-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Centre_name', models.CharField(max_length=100)),
                ('Centre_ID', models.CharField(max_length=20)),
                ('Centre_location', models.CharField(max_length=200)),
            ],
        ),
    ]
