# Generated by Django 3.2.9 on 2022-09-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='centres',
            name='is_open',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
