# Generated by Django 3.2.9 on 2022-09-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centres', '0002_centres_is_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centres',
            name='Centre_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
