# Generated by Django 4.1.3 on 2023-01-27 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentreEnquiryRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_id', models.CharField(max_length=10, unique=True)),
                ('enquiry_status', models.CharField(max_length=1)),
                ('eps_creation_date', models.DateTimeField(null=True)),
                ('eps_completion_date', models.DateTimeField(null=True)),
                ('eps_ack_letter_ind', models.CharField(max_length=1, null=True)),
                ('eps_ses_sid', models.CharField(max_length=5, null=True)),
                ('centre_id', models.CharField(max_length=5, null=True)),
                ('created_by', models.CharField(max_length=50, null=True)),
                ('cie_direct_id', models.CharField(max_length=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_id', models.CharField(max_length=10)),
                ('service', models.CharField(max_length=5)),
                ('component_indicator', models.CharField(max_length=1)),
                ('batch', models.CharField(max_length=10, null=True)),
                ('centre_id', models.CharField(max_length=10)),
                ('candidate_number', models.CharField(max_length=10)),
                ('ass_and_vers', models.CharField(max_length=10)),
                ('assessment_name', models.CharField(max_length=50)),
                ('component_id', models.CharField(max_length=4)),
                ('rm_ind', models.CharField(max_length=10)),
                ('submit_date', models.DateTimeField(null=True)),
                ('bie', models.CharField(max_length=10)),
                ('omr_batch', models.CharField(max_length=10, null=True)),
                ('omr_position', models.CharField(max_length=10, null=True)),
                ('completion_date', models.DateTimeField(null=True)),
                ('initial_check_complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EnquiryBatches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eb_sid', models.CharField(default=0, max_length=8, unique=True)),
                ('created_date', models.DateTimeField(null=True)),
                ('enpe_eper_per_sid', models.CharField(max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnquiryComponents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ec_sid', models.CharField(default=0, max_length=8, unique=True)),
                ('eps_ses_sid', models.CharField(max_length=5, null=True)),
                ('eps_ass_code', models.CharField(max_length=4, null=True)),
                ('eps_ass_ver_no', models.CharField(max_length=2, null=True)),
                ('eps_com_id', models.CharField(max_length=2, null=True)),
                ('eps_qual_id', models.CharField(max_length=5, null=True)),
                ('eps_qual_name', models.CharField(max_length=50, null=True)),
                ('eps_ass_name', models.CharField(max_length=50, null=True)),
                ('eps_comp_name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnquiryPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enpe_sid', models.CharField(default=0, max_length=8, unique=True)),
                ('sp_sid', models.CharField(max_length=8, null=True)),
                ('per_sid', models.CharField(max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(default='', max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=6, null=True)),
                ('task_creation_date', models.DateTimeField(auto_now_add=True)),
                ('task_assigned_to', models.CharField(max_length=150, null=True)),
                ('task_assigned_date', models.DateTimeField(null=True)),
                ('task_completion_date', models.DateTimeField(null=True)),
                ('ec_sid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='script_tasks', to='enquiries.enquirycomponents', to_field='ec_sid')),
                ('enquiry_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiry_tasks', to='enquiries.centreenquiryrequests', to_field='enquiry_id')),
            ],
        ),
        migrations.CreateModel(
            name='ExaminerAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unavailability_start_date', models.DateField(null=True)),
                ('unavailability_end_date', models.DateField(null=True)),
                ('unavailable_2_flag', models.CharField(max_length=1, null=True)),
                ('unavailable_5_flag', models.CharField(max_length=1, null=True)),
                ('unavailable_9_flag', models.CharField(max_length=1, null=True)),
                ('manual_apportion_ind', models.CharField(max_length=1, null=True)),
                ('ea_sid', models.ManyToManyField(related_name='exm_availability', to='enquiries.enquirypersonnel')),
            ],
        ),
        migrations.CreateModel(
            name='EnquiryRequestParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erp_sid', models.CharField(default=0, max_length=8, unique=True)),
                ('service_code', models.CharField(max_length=5, null=True)),
                ('eps_ses_sid', models.CharField(max_length=5, null=True)),
                ('eps_ass_code', models.CharField(max_length=4, null=True)),
                ('eps_ass_ver_no', models.CharField(max_length=2, null=True)),
                ('eps_option_code', models.CharField(max_length=2, null=True)),
                ('eps_cand_unique_id', models.CharField(max_length=20, null=True)),
                ('eps_cand_id', models.CharField(max_length=10, null=True)),
                ('eps_centre_id', models.CharField(max_length=5, null=True)),
                ('eps_comp_ind', models.CharField(max_length=1, null=True)),
                ('eps_script_measure', models.CharField(max_length=8, null=True)),
                ('booked_in_error_ind', models.CharField(max_length=1, null=True)),
                ('cer_sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='enquiries.centreenquiryrequests', to_field='enquiry_id')),
            ],
        ),
        migrations.CreateModel(
            name='EnquiryPersonnelDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sp_sid', models.CharField(max_length=8, null=True)),
                ('ass_code', models.CharField(max_length=8, null=True)),
                ('com_id', models.CharField(max_length=8, null=True)),
                ('sp_name', models.CharField(max_length=100, null=True)),
                ('sp_ses_sid', models.CharField(max_length=8, null=True)),
                ('sp_use_esm_ind', models.CharField(max_length=8, null=True)),
                ('session', models.CharField(max_length=8, null=True)),
                ('exm_creditor_no', models.CharField(max_length=8, null=True)),
                ('exm_examiner_no', models.CharField(max_length=8, null=True)),
                ('spp_sid', models.CharField(max_length=8, null=True)),
                ('per_sid', models.CharField(max_length=8, null=True)),
                ('exm_title', models.CharField(max_length=20, null=True)),
                ('exm_initials', models.CharField(max_length=50, null=True)),
                ('exm_surname', models.CharField(max_length=50, null=True)),
                ('exm_forename', models.CharField(max_length=50, null=True)),
                ('exm_email', models.CharField(max_length=50, null=True)),
                ('ear_approval_ind', models.CharField(max_length=1, null=True)),
                ('panel_size', models.CharField(max_length=8, null=True)),
                ('enpe_sid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exm_per_details', to='enquiries.enquirypersonnel', to_field='enpe_sid')),
            ],
        ),
        migrations.AddField(
            model_name='enquirycomponents',
            name='erp_sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiry_parts', to='enquiries.enquiryrequestparts', to_field='erp_sid'),
        ),
        migrations.CreateModel(
            name='EnquiryComponentElements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ece_status', models.CharField(max_length=20, null=True)),
                ('clerical_mark', models.CharField(max_length=5, null=True)),
                ('mark_after_enquiry', models.CharField(max_length=5, null=True)),
                ('justification_code', models.CharField(max_length=5, null=True)),
                ('eb_sid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='enquiries.enquirybatches', to_field='eb_sid')),
                ('ec_sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enquiries.enquirycomponents', to_field='ec_sid')),
            ],
        ),
    ]
