# Generated by Django 4.1.3 on 2023-01-30 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enquiries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmanager',
            name='task_assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
