# Generated by Django 4.1.3 on 2023-01-31 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0002_alter_taskmanager_task_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examineravailability',
            name='manual_apportion_ind',
        ),
    ]
