# Generated by Django 4.1.3 on 2023-02-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0003_remove_examineravailability_manual_apportion_ind'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueCreditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exm_creditor_no', models.CharField(default=0, max_length=8, unique=True)),
                ('per_sid', models.CharField(default=0, max_length=8, unique=True)),
            ],
        ),
    ]
