# Generated by Django 4.1.3 on 2023-02-02 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0004_uniquecreditor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquirypersonnel',
            name='per_sid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creditors', to='enquiries.uniquecreditor', to_field='per_sid'),
        ),
    ]
