# Generated by Django 4.1.3 on 2023-02-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0005_alter_enquirypersonnel_per_sid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examineravailability',
            name='ea_sid',
        ),
        migrations.AddField(
            model_name='examineravailability',
            name='creditor',
            field=models.ManyToManyField(related_name='exm_availability', to='enquiries.uniquecreditor'),
        ),
    ]
