# Generated by Django 4.1.3 on 2023-02-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0006_remove_examineravailability_ea_sid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquirypersonneldetails',
            name='exm_email',
        ),
        migrations.RemoveField(
            model_name='enquirypersonneldetails',
            name='exm_forename',
        ),
        migrations.RemoveField(
            model_name='enquirypersonneldetails',
            name='exm_initials',
        ),
        migrations.RemoveField(
            model_name='enquirypersonneldetails',
            name='exm_surname',
        ),
        migrations.RemoveField(
            model_name='enquirypersonneldetails',
            name='exm_title',
        ),
        migrations.RemoveField(
            model_name='enquirypersonneldetails',
            name='per_sid',
        ),
        migrations.AddField(
            model_name='uniquecreditor',
            name='exm_email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uniquecreditor',
            name='exm_forename',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uniquecreditor',
            name='exm_initials',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uniquecreditor',
            name='exm_surname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uniquecreditor',
            name='exm_title',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
