# Generated by Django 4.1.3 on 2023-02-03 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0007_remove_enquirypersonneldetails_exm_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptApportionment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ec_sid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apportion_script', to='enquiries.enquirycomponents', to_field='ec_sid')),
                ('enpe_sid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apportion_examiner', to='enquiries.enquirypersonnel', to_field='enpe_sid')),
            ],
        ),
    ]
