# Generated by Django 4.1.3 on 2023-02-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0008_scriptapportionment'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptapportionment',
            name='script_marked',
            field=models.CharField(default=0, max_length=1),
        ),
    ]
