# Generated by Django 4.1.3 on 2023-02-07 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0009_scriptapportionment_script_marked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquirycomponentelements',
            name='eb_sid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_id', to='enquiries.enquirybatches', to_field='eb_sid'),
        ),
        migrations.AlterField(
            model_name='enquirycomponentelements',
            name='ec_sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='script_id', to='enquiries.enquirycomponents', to_field='ec_sid'),
        ),
    ]
