# Generated by Django 4.1.3 on 2023-02-15 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0010_alter_enquirycomponentelements_eb_sid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RpaFailureAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rpa_task_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_manager_task', to='enquiries.taskmanager')),
            ],
        ),
    ]
