# Generated by Django 4.1.3 on 2023-02-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0011_rpafailureaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpafailureaudit',
            name='failure_reason',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
