# Generated by Django 4.1.3 on 2023-02-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0012_rpafailureaudit_failure_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpafailureaudit',
            name='failure_reason',
            field=models.TextField(null=True),
        ),
    ]
