# Generated by Django 4.1.3 on 2023-02-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0013_alter_rpafailureaudit_failure_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquirycomponents',
            name='eps_ses_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
