# Generated by Django 4.1.3 on 2023-03-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0014_enquirycomponents_eps_ses_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExaminerNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_created', models.DateField(auto_now_add=True, null=True)),
                ('creditor', models.ManyToManyField(related_name='exm_notes', to='enquiries.uniquecreditor')),
            ],
        ),
    ]
