# Generated by Django 4.1.3 on 2023-03-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0016_examinernotes_note_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinernotes',
            name='examiner_notes',
            field=models.TextField(null=True),
        ),
    ]
