# Generated by Django 4.1.3 on 2023-03-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0017_examinernotes_examiner_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examinernotes',
            name='note_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
