# Generated by Django 4.1.3 on 2023-03-22 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enquiries', '0018_alter_examinernotes_note_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExaminerConflicts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examiner_conflicts', models.TextField(null=True)),
                ('note_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('note_modified', models.DateTimeField(auto_now=True, null=True)),
                ('creditor', models.ManyToManyField(related_name='exm_conflicts', to='enquiries.uniquecreditor')),
                ('note_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
