# Generated by Django 4.1.3 on 2023-03-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0019_examinerconflicts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExaminerEmailOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examiner_email_manual', models.TextField(null=True)),
                ('creditor', models.ManyToManyField(related_name='exm_email_manual', to='enquiries.uniquecreditor')),
            ],
        ),
    ]
