# Generated by Django 4.1.3 on 2023-04-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0020_examineremailoverride'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquirycomponents',
            name='ccm_measure',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
