# Generated by Django 4.1.3 on 2023-04-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0021_enquirycomponents_ccm_measure'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiryrequestparts',
            name='stud_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
