# Generated by Django 4.1.3 on 2023-04-26 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0022_enquiryrequestparts_stud_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MisReturnData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_exm', models.CharField(max_length=10, null=True)),
                ('rev_exm', models.CharField(max_length=10, null=True)),
                ('original_mark', models.CharField(max_length=10, null=True)),
                ('mark_status', models.CharField(max_length=10, null=True)),
                ('revised_mark', models.CharField(max_length=10, null=True)),
                ('justification_code', models.CharField(max_length=20, null=True)),
                ('eb_sid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_mis', to='enquiries.enquirybatches', to_field='eb_sid')),
                ('ec_sid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='script_mis', to='enquiries.enquirycomponents', to_field='ec_sid')),
            ],
        ),
    ]
