# Generated by Django 4.1.3 on 2023-05-09 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0023_misreturndata'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryComponentsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eps_ses_sid', models.CharField(max_length=5, null=True)),
                ('eps_ass_code', models.CharField(max_length=4, null=True)),
                ('eps_com_id', models.CharField(max_length=2, null=True)),
                ('eps_cnu_id', models.CharField(max_length=5, null=True)),
                ('eps_cand_no', models.CharField(max_length=10, null=True)),
                ('exm_position', models.CharField(max_length=10, null=True)),
                ('kbr_code', models.CharField(max_length=4, null=True)),
                ('kbr_reason', models.CharField(max_length=20, null=True)),
                ('current_mark', models.CharField(max_length=5, null=True)),
                ('ear_mark', models.CharField(max_length=5, null=True)),
                ('ear_mark_alt', models.CharField(max_length=5, null=True)),
                ('cer_sid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiry_original_marks', to='enquiries.centreenquiryrequests', to_field='enquiry_id')),
                ('ec_sid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='script_original_marks', to='enquiries.enquirycomponents', to_field='ec_sid')),
            ],
        ),
    ]
