# Generated by Django 4.1.3 on 2023-05-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0024_enquirycomponentshistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='misreturndata',
            name='final_mark',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
