# Generated by Django 4.1.3 on 2023-05-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0025_misreturndata_final_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='misreturndata',
            name='final_justification_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='misreturndata',
            name='final_mark_status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
