# Generated by Django 4.1.3 on 2023-05-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0027_enquirycomponentsexaminerchecks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquirycomponentsexaminerchecks',
            name='kbr_reason',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='enquirycomponentshistory',
            name='kbr_reason',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
