# Generated by Django 4.1.3 on 2023-05-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0028_alter_enquirycomponentsexaminerchecks_kbr_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquirycomponentsexaminerchecks',
            name='kbr_reason',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='enquirycomponentshistory',
            name='kbr_reason',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
