# Generated by Django 4.1.3 on 2023-05-19 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0029_alter_enquirycomponentsexaminerchecks_kbr_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryComponentsPreviousExaminers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exm_position', models.CharField(max_length=10, null=True)),
                ('cer_sid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiry_prev_exm', to='enquiries.centreenquiryrequests', to_field='enquiry_id')),
                ('ec_sid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='script_prev_exm', to='enquiries.enquirycomponents', to_field='ec_sid')),
            ],
        ),
    ]
