# Generated by Django 4.1.3 on 2023-05-25 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0030_enquirycomponentspreviousexaminers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptApportionmentExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extenstion_days', models.CharField(default=0, max_length=3)),
                ('ec_sid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='script_extension', to='enquiries.enquirycomponents', to_field='ec_sid')),
                ('task_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_extension', to='enquiries.taskmanager')),
            ],
        ),
    ]
