# Generated by Django 4.1.3 on 2023-06-01 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0031_scriptapportionmentextension'),
    ]

    operations = [
        migrations.CreateModel(
            name='EsmcsvDownloads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ec_sid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='script_esmcsv', to='enquiries.enquirycomponents', to_field='ec_sid')),
                ('task_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='esmcsv_task', to='enquiries.taskmanager')),
            ],
        ),
    ]
