# Generated by Django 4.1.3 on 2023-06-01 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0032_esmcsvdownloads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esmcsvdownloads',
            name='ec_sid',
        ),
        migrations.RemoveField(
            model_name='esmcsvdownloads',
            name='task_key',
        ),
    ]
