# Generated by Django 4.1.3 on 2023-06-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0033_remove_esmcsvdownloads_ec_sid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='esmcsvdownloads',
            name='archive_count',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='esmcsvdownloads',
            name='download_count',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
