# Generated by Django 4.1.3 on 2023-06-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0034_esmcsvdownloads_archive_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='esmcsvdownloads',
            name='file_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
