# Generated by Django 4.1.3 on 2023-06-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0035_esmcsvdownloads_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptapportionment',
            name='script_marked',
            field=models.CharField(default=1, max_length=1),
        ),
    ]
