# Generated by Django 4.1.3 on 2023-06-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0036_alter_scriptapportionment_script_marked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptapportionment',
            name='script_marked',
            field=models.IntegerField(default=1),
        ),
    ]
