# Generated by Django 4.1.3 on 2023-06-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0037_alter_scriptapportionment_script_marked'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarServerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
