# Generated by Django 4.1.3 on 2023-06-08 17:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0038_earserversettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='earserversettings',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
