# Generated by Django 4.1.3 on 2023-06-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0039_earserversettings_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='earserversettings',
            name='enquiry_id_list',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='earserversettings',
            name='session_id_list',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
    ]
