# Generated by Django 4.1.3 on 2023-06-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0040_earserversettings_enquiry_id_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='misreturndata',
            name='keying_required',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='misreturndata',
            name='selected_justification_code',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
