# Generated by Django 4.1.3 on 2023-07-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0041_misreturndata_keying_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='misreturndata',
            name='remark_concern_reason',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='misreturndata',
            name='remark_reason',
            field=models.TextField(null=True),
        ),
    ]
