# Generated by Django 4.1.3 on 2023-07-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0042_misreturndata_remark_concern_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquirycomponents',
            name='script_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
