# Generated by Django 4.1.3 on 2023-07-17 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0043_enquirycomponents_script_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryGrades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eps_ass_code', models.CharField(max_length=4, null=True)),
                ('eps_cand_no', models.CharField(max_length=10, null=True)),
                ('previous_grade', models.CharField(max_length=4, null=True)),
                ('previous_seq', models.CharField(max_length=4, null=True)),
                ('new_grade', models.CharField(max_length=4, null=True)),
                ('new_seq', models.CharField(max_length=4, null=True)),
                ('enquiry_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiry_grades', to='enquiries.centreenquiryrequests', to_field='enquiry_id')),
            ],
        ),
    ]
