# Generated by Django 4.1.3 on 2023-07-19 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0044_enquirygrades'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetBIEAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_reason', models.TextField(null=True)),
                ('rpa_task_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_bie_reason', to='enquiries.taskmanager')),
            ],
        ),
    ]
