# Generated by Django 4.1.3 on 2023-07-19 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0045_setbieaudit'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetIssueAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_flag', models.IntegerField(default=1)),
                ('issue_reason', models.TextField(null=True)),
                ('enquiry_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiry_issues', to='enquiries.centreenquiryrequests', to_field='enquiry_id')),
            ],
        ),
    ]
