# Generated by Django 4.1.3 on 2023-07-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0046_setissueaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptapportionment',
            name='apportionment_invalidated',
            field=models.IntegerField(default=0),
        ),
    ]
