# Generated by Django 4.1.3 on 2023-07-26 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enquiries', '0047_scriptapportionment_apportionment_invalidated'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTeams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(default='', max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskUserSecondary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secondary_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enquiries.taskteams')),
                ('task_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskUserPrimary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_status', models.CharField(default='', max_length=2, unique=True)),
                ('primary_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enquiries.taskteams')),
                ('task_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GradeFailureAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_reason', models.TextField(null=True)),
                ('task_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_grade_failure', to='enquiries.taskmanager')),
            ],
        ),
        migrations.AddField(
            model_name='tasktypes',
            name='task_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enquiries.taskteams'),
        ),
    ]
