# Generated by Django 4.1.3 on 2023-07-26 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0048_taskteams_taskusersecondary_taskuserprimary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradefailureaudit',
            name='failure_stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enquiries.tasktypes', to_field='task_id'),
        ),
    ]
