# Generated by Django 4.1.3 on 2023-07-26 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0049_gradefailureaudit_failure_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkTolerances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_tolerance', models.CharField(max_length=4, null=True)),
                ('cer_sid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiry_mark_tolerances', to='enquiries.centreenquiryrequests', to_field='enquiry_id')),
                ('ec_sid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='script_mark_tolerances', to='enquiries.enquirycomponents', to_field='ec_sid')),
            ],
        ),
    ]
