# Generated by Django 4.1.3 on 2023-07-26 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0050_marktolerances'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marktolerances',
            name='cer_sid',
        ),
        migrations.RemoveField(
            model_name='marktolerances',
            name='ec_sid',
        ),
        migrations.AddField(
            model_name='marktolerances',
            name='eps_ass_code',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='marktolerances',
            name='eps_com_id',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
