# Generated by Django 4.1.3 on 2023-07-26 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0051_remove_marktolerances_cer_sid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasktypes',
            name='task_team',
        ),
    ]
