# Generated by Django 4.1.3 on 2023-07-26 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0052_remove_tasktypes_task_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktypes',
            name='task_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enquiries.taskteams'),
        ),
    ]
