# Generated by Django 4.1.3 on 2023-07-26 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0053_tasktypes_task_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktypes',
            name='task_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tasktypes',
            name='task_rank',
            field=models.IntegerField(default=0),
        ),
    ]
