# Generated by Django 4.1.3 on 2023-07-26 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0054_tasktypes_task_description_tasktypes_task_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktypes',
            name='task_id',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
