# Generated by Django 4.1.3 on 2023-07-27 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0055_alter_tasktypes_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskuserprimary',
            name='primary_status',
            field=models.CharField(default='', max_length=2),
        ),
    ]
