# Generated by Django 4.1.3 on 2023-07-27 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0056_alter_taskuserprimary_primary_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptapportionment',
            name='script_mark_entered',
            field=models.IntegerField(default=1),
        ),
    ]
