# Generated by Django 4.1.3 on 2023-07-30 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0057_scriptapportionment_script_mark_entered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmanager',
            name='task_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='all_tasks', to='enquiries.tasktypes', to_field='task_id'),
        ),
    ]
