# Generated by Django 4.1.3 on 2023-07-31 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enquiries', '0059_alter_taskmanager_task_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskuserprimary',
            name='task_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_primary', to=settings.AUTH_USER_MODEL),
        ),
    ]
