# Generated by Django 4.1.3 on 2023-08-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0060_alter_taskuserprimary_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='earserversettings',
            name='session_description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='earserversettings',
            name='enquiry_id_list',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='earserversettings',
            name='session_id_list',
            field=models.TextField(default=''),
        ),
    ]
