# Generated by Django 4.1.3 on 2023-08-04 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0062_pausedenquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_reason', models.TextField(default='')),
                ('enquiry_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priority_enquiries', to='enquiries.centreenquiryrequests', to_field='enquiry_id')),
            ],
        ),
    ]
