# Generated by Django 4.1.3 on 2023-08-06 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0063_priorityenquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_deadline', models.DateTimeField(null=True)),
                ('original_enquiry_deadline', models.DateTimeField(null=True)),
                ('enquiry_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiry_deadline', to='enquiries.centreenquiryrequests', to_field='enquiry_id')),
            ],
        ),
    ]
