# Generated by Django 4.1.3 on 2023-08-07 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0064_enquirydeadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExaminerPanels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ass_code', models.CharField(max_length=8, null=True)),
                ('com_id', models.CharField(max_length=8, null=True)),
                ('manual_apportionment', models.BooleanField(default=False)),
                ('panel_notes', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='uniquecreditor',
            name='panel_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panel_creditors', to='enquiries.examinerpanels'),
        ),
    ]
