# Generated by Django 4.1.3 on 2023-08-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0065_examinerpanels_uniquecreditor_panel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinerpanels',
            name='panel_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='examinerpanels',
            name='panel_size',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='examinerpanels',
            name='ses_sid',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
