# Generated by Django 4.1.3 on 2023-08-07 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0066_examinerpanels_panel_name_examinerpanels_panel_size_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scriptapportionmentextension',
            old_name='extenstion_days',
            new_name='extension_days',
        ),
    ]
