# Generated by Django 4.1.3 on 2023-08-07 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0067_rename_extenstion_days_scriptapportionmentextension_extension_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uniquecreditor',
            name='panel_id',
        ),
        migrations.AddField(
            model_name='enquirypersonneldetails',
            name='panel_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panel_creditors', to='enquiries.examinerpanels'),
        ),
    ]
