# Generated by Django 4.1.3 on 2023-08-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0068_remove_uniquecreditor_panel_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScaledMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eps_ass_code', models.CharField(max_length=4, null=True)),
                ('eps_com_id', models.CharField(max_length=2, null=True)),
                ('eps_cnu_id', models.CharField(max_length=10, null=True)),
                ('eps_cand_no', models.CharField(max_length=10, null=True)),
                ('raw_mark', models.CharField(max_length=10, null=True)),
                ('assessor_mark', models.CharField(max_length=10, null=True)),
                ('final_mark', models.CharField(max_length=10, null=True)),
                ('scaled_mark', models.CharField(max_length=10, null=True)),
                ('original_exm_scaled', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
