# Generated by Django 4.1.3 on 2023-08-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0069_scaledmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='scaledmarks',
            name='exm_examiner_no',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
