# Generated by Django 4.1.3 on 2023-08-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0070_scaledmarks_exm_examiner_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='misreturndata',
            name='keyed_mark_status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
