# Generated by Django 4.1.3 on 2023-08-19 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0071_misreturndata_keyed_mark_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentreEnquiryRequestsExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_id', models.CharField(max_length=10, unique=True)),
                ('enquiry_status', models.CharField(max_length=1)),
                ('eps_creation_date', models.DateTimeField(null=True)),
                ('eps_completion_date', models.DateTimeField(null=True)),
                ('eps_ack_letter_ind', models.CharField(max_length=1, null=True)),
                ('eps_ses_sid', models.CharField(max_length=5, null=True)),
                ('centre_id', models.CharField(max_length=5, null=True)),
                ('created_by', models.CharField(max_length=50, null=True)),
                ('cie_direct_id', models.CharField(max_length=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnquiryRequestPartsExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erp_sid', models.CharField(default=0, max_length=8, unique=True)),
                ('service_code', models.CharField(max_length=5, null=True)),
                ('eps_ses_sid', models.CharField(max_length=5, null=True)),
                ('eps_ass_code', models.CharField(max_length=4, null=True)),
                ('eps_ass_ver_no', models.CharField(max_length=2, null=True)),
                ('eps_option_code', models.CharField(max_length=2, null=True)),
                ('eps_cand_unique_id', models.CharField(max_length=20, null=True)),
                ('eps_cand_id', models.CharField(max_length=10, null=True)),
                ('eps_centre_id', models.CharField(max_length=5, null=True)),
                ('eps_comp_ind', models.CharField(max_length=1, null=True)),
                ('eps_script_measure', models.CharField(max_length=8, null=True)),
                ('booked_in_error_ind', models.CharField(max_length=1, null=True)),
                ('stud_name', models.CharField(max_length=100, null=True)),
                ('cer_sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_erp', to='enquiries.centreenquiryrequestsextra', to_field='enquiry_id')),
            ],
        ),
        migrations.CreateModel(
            name='EnquiryComponentsExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ec_sid', models.CharField(default=0, max_length=8, unique=True)),
                ('eps_ses_sid', models.CharField(max_length=5, null=True)),
                ('eps_ses_name', models.CharField(max_length=30, null=True)),
                ('eps_ass_code', models.CharField(max_length=4, null=True)),
                ('eps_ass_ver_no', models.CharField(max_length=2, null=True)),
                ('eps_com_id', models.CharField(max_length=2, null=True)),
                ('eps_qual_id', models.CharField(max_length=5, null=True)),
                ('eps_qual_name', models.CharField(max_length=50, null=True)),
                ('eps_ass_name', models.CharField(max_length=50, null=True)),
                ('eps_comp_name', models.CharField(max_length=50, null=True)),
                ('ccm_measure', models.CharField(max_length=5, null=True)),
                ('script_type', models.CharField(max_length=50, null=True)),
                ('erp_sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_ec', to='enquiries.enquiryrequestpartsextra', to_field='erp_sid')),
            ],
        ),
    ]
