# Generated by Django 4.1.3 on 2023-08-31 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0072_centreenquiryrequestsextra_enquiryrequestpartsextra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='misreturndata',
            name='error_status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
