# Generated by Django 4.1.3 on 2023-09-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0073_misreturndata_error_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='misreturndata',
            name='error_status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
