# Generated by Django 4.1.3 on 2023-09-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0074_alter_misreturndata_error_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiryrequestparts',
            name='grade_confirmed_ind',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
