# Generated by Django 4.1.3 on 2023-10-30 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enquiries', '0076_omrchedownloads'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_comment_text', models.TextField()),
                ('task_comment_creation_date', models.DateTimeField(auto_now_add=True)),
                ('task_comment_invalid', models.IntegerField(default=0)),
                ('task_comment_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commented_tasks', to=settings.AUTH_USER_MODEL)),
                ('task_pk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_comments', to='enquiries.taskmanager')),
            ],
        ),
    ]
