# Generated by Django 4.1.3 on 2023-11-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0077_taskcomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmanager',
            name='task_queued',
            field=models.IntegerField(default=0),
        ),
    ]
