# Generated by Django 4.1.3 on 2023-12-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0078_taskmanager_task_queued'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinerpanels',
            name='currently_valid',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='uniquecreditor',
            name='currently_valid',
            field=models.BooleanField(default=1),
        ),
    ]
