# Generated by Django 4.1.3 on 2023-12-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0079_examinerpanels_currently_valid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uniquecreditor',
            name='currently_valid',
        ),
        migrations.AddField(
            model_name='enquirypersonnel',
            name='currently_valid',
            field=models.BooleanField(default=1),
        ),
    ]
