# Generated by Django 4.1.3 on 2023-12-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0080_remove_uniquecreditor_currently_valid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='centreenquiryrequests',
            name='ministry_flag',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
