# Generated by Django 4.1.3 on 2024-01-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0081_centreenquiryrequests_ministry_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiryrequestparts',
            name='grade_change_ind',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
