# Generated by Django 4.1.3 on 2024-01-09 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0082_enquiryrequestparts_grade_change_ind'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiryrequestparts',
            old_name='grade_change_ind',
            new_name='grade_changed_ind',
        ),
    ]
