# Generated by Django 4.1.3 on 2024-01-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0083_rename_grade_change_ind_enquiryrequestparts_grade_changed_ind'),
    ]

    operations = [
        migrations.AddField(
            model_name='scaledmarks',
            name='eps_ses_sid',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
