# Generated by Django 4.1.3 on 2024-01-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0084_scaledmarks_eps_ses_sid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualTaskQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(max_length=6, null=True)),
                ('task_creation_date', models.DateTimeField(auto_now_add=True)),
                ('task_completion_date', models.DateTimeField(null=True)),
                ('task_queued', models.IntegerField(default=1)),
            ],
        ),
    ]
