# Generated by Django 4.1.3 on 2024-01-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0085_manualtaskqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquirycomponentelements',
            name='clerical_mark_changed_ind',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='enquirycomponentelements',
            name='clerical_mark_confirmed_ind',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='enquirycomponentelements',
            name='omr_mark_changed_ind',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='enquirycomponentelements',
            name='omr_mark_confirmed_ind',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
