# Generated by Django 4.1.3 on 2024-02-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0086_enquirycomponentelements_clerical_mark_changed_ind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualtaskqueue',
            name='task_running',
            field=models.IntegerField(default=0),
        ),
    ]
