# Generated by Django 4.1.3 on 2024-03-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0087_manualtaskqueue_task_running'),
    ]

    operations = [
        migrations.CreateModel(
            name='EsmscrDownloads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents/')),
                ('file_name', models.CharField(max_length=50, null=True)),
                ('download_count', models.CharField(max_length=3, null=True)),
                ('archive_count', models.CharField(max_length=3, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
