# Generated by Django 4.1.3 on 2024-04-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0090_omrscrdownloads'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquirycomponentshistory',
            name='omr_batch',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='enquirycomponentshistory',
            name='omr_position',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
