# Generated by Django 4.1.3 on 2024-05-15 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0091_enquirycomponentshistory_omr_batch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoStagingTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_sid', models.CharField(max_length=20, null=True)),
                ('pan_sid', models.CharField(max_length=20, null=True)),
                ('copied_to_est', models.IntegerField(default=0)),
                ('error_status', models.CharField(max_length=50, null=True)),
                ('comments', models.CharField(max_length=50, null=True)),
                ('eb_sid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staging_batch', to='enquiries.enquirybatches', to_field='eb_sid')),
                ('ec_sid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staging_script', to='enquiries.enquirycomponents', to_field='ec_sid')),
                ('enpe_sid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staging_examiner', to='enquiries.enquirypersonnel', to_field='enpe_sid')),
            ],
        ),
    ]
