# Generated by Django 4.1.3 on 2024-05-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0093_djangostagingtableapp_djangostagingtablemar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='earserversettings',
            name='delta_load_status',
            field=models.TextField(default=''),
        ),
    ]
