# Generated by Django 4.1.3 on 2024-06-19 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enquiries', '0094_earserversettings_delta_load_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptapportionment',
            name='overdue_case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_apportioned_scripts', to='enquiries.enquirycomponents'),
        ),
        migrations.CreateModel(
            name='ExaminerOverdueCases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_creation_date', models.DateTimeField(auto_now_add=True)),
                ('task_assigned_date', models.DateTimeField(null=True)),
                ('task_completion_date', models.DateTimeField(null=True)),
                ('task_queued', models.IntegerField(default=0)),
                ('task_assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
