# Generated by Django 4.1.3 on 2024-06-19 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0095_scriptapportionment_overdue_case_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scriptapportionmentextension',
            name='task_id',
        ),
        migrations.AddField(
            model_name='scriptapportionmentextension',
            name='case_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_extension', to='enquiries.examineroverduecases'),
        ),
    ]
