# Generated by Django 4.1.3 on 2024-06-24 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0096_remove_scriptapportionmentextension_task_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptapportionment',
            name='overdue_case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_apportioned_scripts', to='enquiries.examineroverduecases'),
        ),
    ]
