# Generated by Django 4.1.3 on 2024-06-25 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0097_alter_scriptapportionment_overdue_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='examineroverduecases',
            name='enpe_sid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overdue_examiner', to='enquiries.enquirypersonnel', to_field='enpe_sid'),
        ),
    ]
