# Generated by Django 4.1.3 on 2024-06-26 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enquiries', '0098_examineroverduecases_enpe_sid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_comment_text', models.TextField()),
                ('case_comment_creation_date', models.DateTimeField(auto_now_add=True)),
                ('case_comment_invalid', models.IntegerField(default=0)),
                ('case_comment_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commented_cases', to=settings.AUTH_USER_MODEL)),
                ('case_pk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_comments', to='enquiries.taskmanager')),
            ],
        ),
    ]
