# Generated by Django 4.1.3 on 2024-06-26 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0099_casecomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casecomments',
            name='case_pk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_comments', to='enquiries.examineroverduecases'),
        ),
    ]
