# Generated by Django 4.1.3 on 2024-08-07 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0101_enquirycomponentshistoryspecial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnquiryComponentsHistorySpecial',
        ),
    ]
