# Generated by Django 5.0.6 on 2024-11-05 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enquiries", "0102_delete_enquirycomponentshistoryspecial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="djangostagingtableapp",
            name="pan_sid",
        ),
        migrations.RemoveField(
            model_name="djangostagingtableapp",
            name="per_sid",
        ),
        migrations.RemoveField(
            model_name="djangostagingtablemar",
            name="justification_code",
        ),
        migrations.RemoveField(
            model_name="djangostagingtablemar",
            name="outcome_status",
        ),
        migrations.AddField(
            model_name="djangostagingtableapp",
            name="com_id",
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="djangostagingtableapp",
            name="ear_mark",
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name="djangostagingtableapp",
            name="enquiry_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staging_enquiry_id",
                to="enquiries.centreenquiryrequests",
                to_field="enquiry_id",
            ),
        ),
        migrations.AddField(
            model_name="djangostagingtableapp",
            name="eps_ass_code",
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="djangostagingtableapp",
            name="eps_ass_ver_no",
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="djangostagingtableapp",
            name="eps_cand_id",
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name="djangostagingtableapp",
            name="eps_centre_id",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="djangostagingtableapp",
            name="eps_creation_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="djangostagingtableapp",
            name="eps_ses_sid",
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name="djangostagingtableapp",
            name="me_id",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="djangostagingtablemar",
            name="eps_cand_id",
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name="djangostagingtablemar",
            name="eps_centre_id",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="djangostagingtablemar",
            name="mark_confirmed_ind",
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="djangostagingtablemar",
            name="scaled_mark",
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name="djangostagingtablemar",
            name="selected_justification_code",
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="enquirycomponentelements",
            name="me_id",
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name="djangostagingtablemar",
            name="final_mark",
            field=models.CharField(max_length=7, null=True),
        ),
    ]
