# Generated by Django 3.2.9 on 2024-11-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0103_remove_djangostagingtableapp_pan_sid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangostagingtableapp',
            name='comments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='djangostagingtableapp',
            name='error_status',
            field=models.TextField(null=True),
        ),
    ]
