# Generated by Django 4.2.17 on 2024-12-18 14:09

from django.db import migrations
import psqlextra.indexes.conditional_unique_index


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0104_auto_20241113_1339'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='taskmanager',
            index=psqlextra.indexes.conditional_unique_index.ConditionalUniqueIndex(condition='"task_id"="INITCH"', fields=['enquiry_id', 'task_id'], name='enq-task'),
        ),
    ]
