# Generated by Django 4.2.17 on 2024-12-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0105_taskmanager_enq_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquirydeadline',
            name='unique_enquiry_id',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
