# Generated by Django 4.2.17 on 2024-12-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0106_enquirydeadline_unique_enquiry_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinerpanels',
            name='ses_ass_com',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
