# Generated by Django 4.2.17 on 2025-01-24 16:11

from django.db import migrations, models
import psqlextra.indexes.conditional_unique_index


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0107_examinerpanels_ses_ass_com'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='centreenquiryrequests',
            index=models.Index(fields=['enquiry_id'], name='enquiries_c_enquiry_79d566_idx'),
        ),
        migrations.AddIndex(
            model_name='enquirybatches',
            index=models.Index(fields=['eb_sid'], name='enquiries_e_eb_sid_031009_idx'),
        ),
        migrations.AddIndex(
            model_name='enquirycomponentelements',
            index=models.Index(fields=['ec_sid'], name='enquiries_e_ec_sid__68175e_idx'),
        ),
        migrations.AddIndex(
            model_name='enquirycomponentelements',
            index=models.Index(fields=['eb_sid'], name='enquiries_e_eb_sid__bc6f90_idx'),
        ),
        migrations.AddIndex(
            model_name='enquirycomponents',
            index=models.Index(fields=['ec_sid'], name='enquiries_e_ec_sid_e7efcc_idx'),
        ),
        migrations.AddIndex(
            model_name='enquirycomponents',
            index=models.Index(fields=['erp_sid'], name='enquiries_e_erp_sid_a82010_idx'),
        ),
        migrations.AddIndex(
            model_name='enquirycomponentsexaminerchecks',
            index=models.Index(fields=['cer_sid'], name='enquiries_e_cer_sid_12dd10_idx'),
        ),
        migrations.AddIndex(
            model_name='enquirycomponentsexaminerchecks',
            index=models.Index(fields=['ec_sid'], name='enquiries_e_ec_sid__73e901_idx'),
        ),
        migrations.AddIndex(
            model_name='enquirycomponentshistory',
            index=models.Index(fields=['cer_sid'], name='enquiries_e_cer_sid_209931_idx'),
        ),
        migrations.AddIndex(
            model_name='enquirycomponentshistory',
            index=models.Index(fields=['ec_sid'], name='enquiries_e_ec_sid__b5c44b_idx'),
        ),
        migrations.AddIndex(
            model_name='enquirycomponentspreviousexaminers',
            index=models.Index(fields=['cer_sid'], name='enquiries_e_cer_sid_d96858_idx'),
        ),
        migrations.AddIndex(
            model_name='enquirycomponentspreviousexaminers',
            index=models.Index(fields=['ec_sid'], name='enquiries_e_ec_sid__a4c011_idx'),
        ),
        migrations.AddIndex(
            model_name='enquiryrequestparts',
            index=models.Index(fields=['erp_sid'], name='enquiries_e_erp_sid_0d7e41_idx'),
        ),
        migrations.AddIndex(
            model_name='enquiryrequestparts',
            index=models.Index(fields=['cer_sid'], name='enquiries_e_cer_sid_8347d1_idx'),
        ),
        migrations.AddIndex(
            model_name='misreturndata',
            index=models.Index(fields=['ec_sid'], name='enquiries_m_ec_sid__3ca91a_idx'),
        ),
        migrations.AddIndex(
            model_name='misreturndata',
            index=models.Index(fields=['eb_sid'], name='enquiries_m_eb_sid__ec223f_idx'),
        ),
        migrations.AddIndex(
            model_name='scriptapportionment',
            index=models.Index(fields=['ec_sid'], name='enquiries_s_ec_sid__be00bc_idx'),
        ),
        migrations.AddIndex(
            model_name='taskmanager',
            index=models.Index(fields=['enquiry_id'], name='enquiries_t_enquiry_b9da5f_idx'),
        ),
        migrations.AddIndex(
            model_name='taskmanager',
            index=models.Index(fields=['ec_sid'], name='enquiries_t_ec_sid__ace07f_idx'),
        ),
        migrations.AddIndex(
            model_name='taskmanager',
            index=models.Index(fields=['task_id'], name='enquiries_t_task_id_b9ae06_idx'),
        ),
    ]
