# Generated by Django 4.2.17 on 2025-02-17 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0108_centreenquiryrequests_enquiries_c_enquiry_79d566_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=200)),
                ('email_name', models.CharField(max_length=200)),
                ('send_date', models.DateField(auto_now_add=True)),
                ('email_sent', models.IntegerField(default=0)),
                ('exm_creditor_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exm_emails_sent', to='enquiries.uniquecreditor', to_field='exm_creditor_no')),
            ],
        ),
        migrations.CreateModel(
            name='MailingListScripts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('service_code', models.CharField(max_length=4)),
                ('syll_comp', models.CharField(max_length=7)),
                ('centre_id', models.CharField(max_length=5)),
                ('candidate_id', models.CharField(max_length=5)),
                ('eb_sid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_emails', to='enquiries.enquirybatches', to_field='eb_sid')),
                ('ec_sid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='script_emails', to='enquiries.enquirycomponents', to_field='ec_sid')),
                ('mailing_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exm_email_scripts', to='enquiries.mailinglist')),
            ],
        ),
    ]
