# Generated by Django 4.1.3 on 2024-11-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllSessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=5)),
                ('session_name', models.TextField()),
                ('valid_session', models.IntegerField()),
            ],
        ),
    ]
