# Generated by Django 4.1.3 on 2024-11-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdq', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allsessions',
            name='valid_session',
        ),
        migrations.AddField(
            model_name='allsessions',
            name='session_sequence',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allsessions',
            name='session_year',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
