# Generated by Django 4.1.3 on 2024-11-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdq', '0002_remove_allsessions_valid_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allsessions',
            name='session_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='allsessions',
            name='session_sequence',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='allsessions',
            name='session_year',
            field=models.IntegerField(null=True),
        ),
    ]
