# Generated by Django 4.1.3 on 2024-11-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdq', '0003_alter_allsessions_session_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allsessions',
            name='session_name',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='allsessions',
            name='session_sequence',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='allsessions',
            name='session_year',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
