# Generated by Django 4.1.3 on 2024-11-05 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdq', '0004_alter_allsessions_session_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allsessions',
            options={'ordering': ['session_year', 'session_sequence']},
        ),
    ]
