# Generated by Django 4.1.3 on 2024-11-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdq', '0005_alter_allsessions_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDQSessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=5)),
                ('session_name', models.TextField(default=None, null=True)),
                ('session_year', models.IntegerField(default=None, null=True)),
                ('session_sequence', models.IntegerField(default=None, null=True)),
                ('results_release_datetime', models.DateTimeField()),
            ],
        ),
    ]
