# Generated by Django 4.1.3 on 2024-11-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdq', '0006_pdqsessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdqsessions',
            name='visible_session',
            field=models.IntegerField(default=1),
        ),
    ]
