# Generated by Django 4.1.3 on 2024-11-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdq', '0007_pdqsessions_visible_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdqsessions',
            name='session_id',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
