# Generated by Django 4.1.3 on 2024-11-07 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdq', '0008_alter_pdqsessions_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDQEntries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centre_number', models.CharField(max_length=5)),
                ('candidate_id', models.CharField(max_length=6)),
                ('syllabus_code', models.CharField(max_length=4)),
                ('component_id', models.CharField(max_length=2)),
                ('syllabus_grade', models.CharField(max_length=3)),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_entries', to='pdq.pdqsessions', to_field='session_id')),
            ],
        ),
    ]
