# Generated by Django 4.1.3 on 2024-11-11 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdq', '0009_pdqentries'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdqentries',
            options={'ordering': ['session_id', 'centre_number']},
        ),
        migrations.AlterModelOptions(
            name='pdqsessions',
            options={'ordering': ['session_year', 'session_sequence']},
        ),
        migrations.CreateModel(
            name='PDQStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_download', models.BooleanField(default=False)),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entry_stage', to='pdq.pdqentries')),
            ],
            options={
                'ordering': ['entry'],
            },
        ),
    ]
