# Generated by Django 4.1.3 on 2024-11-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdq', '0010_alter_pdqentries_options_alter_pdqsessions_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDQcsvDownloads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents/')),
                ('file_name', models.CharField(max_length=50, null=True)),
                ('download_count', models.CharField(max_length=3, null=True)),
                ('archive_count', models.CharField(max_length=3, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
